export const food = [
  { name: 'pancake', main: '-', type: 'baked goods', time: 2 },
  { name: 'eggroll', main: 'ham', type: 'baked goods', time: 2 },
  { name: 'bruchetta', main: '', type: 'baked goods', time: 2 },
  { name: 'blue cheese rosemary crown', main: '', type: 'baked goods', time: 3 },
  { name: 'pot bread', main: '', type: 'baked goods', time: 2 },
  { name: 'lasagna', main: 'beef', type: 'oven dishes', time: 3 },
  { name: 'sausage sauce ', main: 'sausage', type: 'cozy', time: 2 },
  { name: 'pyttipannu ', main: 'sausage ', type: 'cozy', time: 1 },
  { name: 'stuffed chicken breast ', main: 'chicken', type: 'cozy', time: 2 },
  { name: 'beetroot gratin', main: 'vegetable', type: 'cozy', time: 2 },
  { name: 'jacket potatoe', main: 'ham', type: 'cozy', time: 3 },
  { name: 'Greek feast (oven potatoes, tzatziki,  hummus, meatballs, oven bread,)', main: '', type: 'feast', time: 3 },
  { name: 'oven chicken', main: 'chicken', type: 'oven dishes', time: 3 },
  { name: 'moussaka ', main: 'beef', type: 'oven dishes', time: 3 },
  { name: 'makaronilaatikko', main: 'beef', type: 'oven dishes', time: 3 },
  { name: 'stew', main: 'beef', type: 'oven dishes', time: 3 },
  { name: 'Tuscan butter gnocchi', main: 'vegetable', type: 'oven dishes', time: 3 },
  { name: 'stir fry ', main: 'chicken ', type: 'pan mix', time: 2 },
  { name: 'Moroccan Couscous', main: 'chicken', type: 'pan mix', time: 2 },
  { name: 'salmon and spinach pasta', main: 'fish', type: 'pasta', time: 1 },
  { name: 'adzika pasta', main: 'beef', type: 'pasta', time: 1 },
  { name: 'meatball spaghetti', main: 'beef', type: 'pasta', time: 1 },
  { name: 'pesto bacon mozzarella pasta', main: 'bacon', type: 'pasta', time: 1 },
  { name: 'avocado pasta', main: 'vegetable', type: 'pasta', time: 1 },
  { name: 'carbonara ', main: 'bacon', type: 'pasta', time: 2 },
  { name: 'bacon & leek pie', main: 'bacon', type: 'pie', time: 2 },
  { name: 'butter dough meat pie ', main: 'beef', type: 'pie', time: 3 },
  { name: 'peach-chili-ginger chicken ', main: 'chicken', type: 'rice', time: 2 },
  { name: 'chicken curry a la Lene', main: 'chicken', type: 'rice', time: 2 },
  { name: 'blue curry can', main: 'chicken', type: 'rice', time: 2 },
  { name: 'risotto ', main: 'vegetable', type: 'rice', time: 2 },
  { name: 'sushi bowl', main: 'fish', type: 'rice', time: 2 },
  { name: 'pasta  salad', main: 'chicken', type: 'salad', time: 2 },
  { name: 'couscous salad', main: 'vegetable', type: 'salad', time: 2 },
  { name: 'blue cheese salad', main: 'cheese', type: 'salad', time: 1 },
  { name: 'halloumi salad', main: 'cheese', type: 'salad', time: 1 },
  { name: 'potatoes parcels', main: 'vegetable', type: 'sides', time: 2 },
  { name: 'filled mushrooms', main: 'vegetable', type: 'sides', time: 2 },
  { name: 'asparagus with bacon', main: 'vegetable', type: 'sides', time: 2 },
  { name: 'lentil soup ', main: 'vegetable', type: 'soup', time: 2 },
  { name: 'potato leek soup', main: 'vegetable', type: 'soup', time: 2 },
  { name: 'chicken soup', main: 'chicken', type: 'soup', time: 2 },
  { name: 'chorizo soup', main: 'sausage', type: 'soup', time: 2 },
  { name: 'tomato soup w/ baguette', main: 'vegetable', type: 'soup', time: 1 },
  { name: 'spinach soup and eggs', main: 'vegetable', type: 'soup', time: 1 },
  { name: 'steak and taters', main: 'beef', type: 'steak', time: 2 },
  { name: 'club sandwich', main: 'chicken', type: 'street food', time: 1 },
  { name: 'burger', main: 'beef', type: 'street food', time: 1 },
  { name: 'hotdog', main: 'sausage', type: 'street food', time: 1 },
  { name: 'tortilla', main: 'beef', type: 'street food', time: 1 },
  { name: 'pita', main: 'beef', type: 'street food', time: 1 },
  { name: 'chicken wings', main: 'chicken', type: 'street food', time: 3 },
  { name: 'frittata ', main: 'vegetable', type: 'street food', time: 2 },
  { name: 'tortilla omelette ', main: 'ham', type: 'street food', time: 1 },
  { name: 'Tater salat n weiners', main: 'sausage', type: 'street food', time: 1 },
  { name: 'pølsehorn', main: 'sausage', type: 'street food', time: 3 },
]